## Pythonのヴァージョン確認

```bash
$ python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```


## HELLO WORLD

In [1]:
print('Hello World')

Hello World


In [2]:
def main():
    print('Hello World')

if __name__ == "__main__":
    main()

Hello World


## `list`

- `list` は `Python`における配列
- 可変長であり，大きさを宣言する必要はない
- どんな型でも要素として追加できる

#### 初期化 (宣言）
- 型を宣言する必要はない. 右辺に対応して型付けしてくれる. (動的型付け)

In [3]:
lst = []                     #空の配列
lst = [0, 0, 0]              #要素をカンマで区切って入れる
lst = [0 for i in range(3)]  #range()というイテレータを用いたリスト内包表記 (速い)
lst = list(range(3))         #list()というコンストラクタを用いた初期化 (かなり速い)

#### 要素の追加
まずは`list`の初期化.

In [4]:
lst = [1, 2, 3, 4]
print(lst)

[1, 2, 3, 4]


In [5]:
lst.append(5)                #末尾に要素を追加. 破壊的メソッド.
print(lst)

[1, 2, 3, 4, 5]


In [6]:
lst.insert(0, 1)             #インデックス(0)を指定して整数(1)を挿入. 
print(lst)

[1, 1, 2, 3, 4, 5]


##### `python`の標準機能一覧

- `print()` とりあえずなんでも型に合わせて整形して出力してくれる
- `dir()`   その型で使える関数(メソッド)を`list`で返してくれる
- `help()`  説明が出力される. インタープリタだと`vi`で起動されるので`hjkl`で移動，終了は`q`
- `type()`  そのインスタンスの型を`str`(文字列)で返してくれる

In [7]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [8]:
help(list.append)

Help on method_descriptor:

append(...)
    L.append(object) -> None -- append object to end



In [9]:
lst = [1, 2, 3]
type(lst)

list

## `numpy`を使おう

- `python`の算術用ライブラリ
- 高速な行列演算，豊富な関数が魅力

In [10]:
import numpy as np            #numpyをnpという名前でimportして利用する

In [11]:
print(dir(np))                #numpyで定義された関数その他を出力

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_import_tools', '_mat', 'abs', 'absolute', 'absolute_import', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'ad

### 多次元配列 `np.ndarray`

In [12]:
print(dir(np.ndarray))                 #np.ndarray用に定義された関数その他

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '_

### `list`と`np.ndarray`の処理時間を比較


まずはn個の配列を初期化するメソッドで比較

In [13]:
def lst_init(n):
    """ listを用いた実装 """
    lst = list(range(n))
    return lst
    
def array_init(n):
    """ numpyを用いた実装 """
    array = np.arange(n)
    return array

`%timeit`で計測

In [14]:
%timeit lst_init(10000)

229 µs ± 6.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
%timeit array_init(10000)

6.63 µs ± 269 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


配列の要素を合算する`sum`と`np.sum`で比較

In [16]:
%timeit sum(lst_init(10000))

292 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit np.sum(array_init(10000))

15.3 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### `np.ndarray`の初期化方法

### 一次元

In [18]:
array = np.array([1, 2, 3, 4])      #listをnp.array()に代入する
print(array)

[1 2 3 4]


In [19]:
array = np.arange(1,5)              #等差行列を返すnp.arange()を使う
print(array)

[1 2 3 4]


In [20]:
array = np.zeros(4)                 #要素が全て0の行列
print(array)

[ 0.  0.  0.  0.]


In [21]:
array = np.ones(4)                 #要素が全て1の行列
print(array)

[ 1.  1.  1.  1.]


### 多次元

In [22]:
array = np.array([[1,2],[3,4]])         #listを中身にもつlistをnp.array()に代入
print(array)

[[1 2]
 [3 4]]


In [23]:
array = np.arange(1,5).reshape(2,2)     #reshape()で変形
print(array)

[[1 2]
 [3 4]]


In [24]:
array = np.zeros([2,2])                 #np.zeros()にlistを入れると多次元に
print(array)

[[ 0.  0.]
 [ 0.  0.]]


In [25]:
array = np.ones([2,3])                 #np.ones()にlistを入れると多次元に
print(array)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [26]:
array = np.identity(3)                 #np.identityは単位行列
print(array)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### `np.ndarray`の行列演算 (Element-Wise)